modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="minenorth_eurobank"
version="${mod_version}"
displayName="Euro Bank MineNorthRP"
description='''Système bancaire en euros : pièces, billets, distributeurs (ATM) et cartes bancaires.'''

[[dependencies.eurobank]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.eurobank]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
